steps:
  # Build the container image
  - name: 'gcr.io/cloud-builders/docker'
    args: 
      - 'build'
      - '-t'
      - 'gcr.io/$PROJECT_ID/iqore-chatbot:$COMMIT_SHA'
      - '--build-arg'
      - 'OPENAI_API_KEY=${_OPENAI_API_KEY}'
      - '--build-arg'
      - 'MONGODB_URI=${_MONGODB_URI}'
      - '--build-arg'
      - 'MONGODB_DATABASE=${_MONGODB_DATABASE}'
      - '.'
  
  # Push the container image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/iqore-chatbot:$COMMIT_SHA']
  
  # Deploy container image to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'iqoregpt'
      - '--image'
      - 'gcr.io/$PROJECT_ID/iqore-chatbot:$COMMIT_SHA'
      - '--region'
      - 'europe-west1'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
      - '--memory'
      - '512Mi'
      - '--cpu'
      - '1'
      - '--max-instances'
      - '10'
      - '--timeout'
      - '300'
      - '--concurrency'
      - '80'
      - '--set-env-vars'
      - 'OPENAI_API_KEY=${_OPENAI_API_KEY},MONGODB_URI=${_MONGODB_URI},MONGODB_DATABASE=${_MONGODB_DATABASE}'

# Store images in Google Container Registry
images:
  - 'gcr.io/$PROJECT_ID/iqore-chatbot:$COMMIT_SHA'

# Build timeout
timeout: '1200s' 